interface EmailConfig {
  apiKey: string
  from: string
  to: string
}

interface ResendPayload {
  from: string
  to: string[]
  subject: string
  html: string
}

function wrapInTemplate(html: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <style>
    body {
      margin: 0;
      padding: 0;
      background-color: #f3f4f6;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      font-size: 15px;
      color: #1f2937;
    }
    .outer {
      width: 100%;
      padding: 32px 16px;
      box-sizing: border-box;
    }
    .card {
      max-width: 600px;
      margin: 0 auto;
      background: #ffffff;
      border-radius: 12px;
      padding: 32px;
      box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    }
    h1 { font-size: 22px; font-weight: 700; margin: 0 0 20px; color: #111827; }
    h2 { font-size: 17px; font-weight: 600; margin: 24px 0 8px; color: #111827; border-bottom: 1px solid #e5e7eb; padding-bottom: 6px; }
    h3 { font-size: 15px; font-weight: 600; margin: 16px 0 6px; color: #374151; }
    p { margin: 0 0 12px; line-height: 1.6; }
    ul { margin: 0 0 12px; padding-left: 20px; }
    li { margin-bottom: 4px; line-height: 1.6; }
    .metric { display: inline-block; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 10px 16px; margin: 4px 4px 4px 0; }
    .metric-label { font-size: 12px; color: #6b7280; display: block; }
    .metric-value { font-size: 20px; font-weight: 700; color: #111827; }
    .score-great { color: #059669; }
    .score-good { color: #0284c7; }
    .score-low { color: #dc2626; }
    .verdict { background: #f0fdf4; border-left: 4px solid #22c55e; border-radius: 0 8px 8px 0; padding: 14px 18px; margin: 16px 0; }
    .verdict p { margin: 0; }
    .footer { margin-top: 28px; font-size: 12px; color: #9ca3af; text-align: center; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
    th { text-align: left; font-size: 12px; color: #6b7280; font-weight: 600; padding: 6px 8px; border-bottom: 1px solid #e5e7eb; }
    td { padding: 7px 8px; font-size: 14px; border-bottom: 1px solid #f3f4f6; }
    tr:last-child td { border-bottom: none; }
  </style>
</head>
<body>
  <div class="outer">
    <div class="card">
      ${html}
      <div class="footer">Generated by health-reporting · Cloudflare Workers AI</div>
    </div>
  </div>
</body>
</html>`
}

export async function sendEmail(
  config: EmailConfig,
  subject: string,
  html: string,
): Promise<void> {
  const payload: ResendPayload = {
    from: config.from,
    to: [config.to],
    subject,
    html: wrapInTemplate(html),
  }

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${config.apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  })

  if (!res.ok) {
    const text = await res.text()
    throw new Error(`Resend API error ${res.status}: ${text}`)
  }
}
